spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estudo
    username: postgres
    password: Ivb8919I
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
